lm_conf:
    nlayers: 4
    unit: 2048
    tie_weights: true
    dropout_rate: 0.2
optim: adam
optim_conf:
    lr: 0.001
batch_type: folded
batch_size: 400   # batch size in LM training
max_epoch: 30     # if the data size is large, we can reduce this
patience: 3

best_model_criterion:
-   - valid
    - loss
    - min
#keep_nbest_models: 1
keep_nbest_models: 5